### ISSUE TITLE
作者能把设计思路和核心代码在README里体现出来吗

### ISSUE THREAD

**Issue by Vibing** [bbxjs/bbx#2]
如题，谢谢，因为我看你代码似乎还没写完

**Comment by zinkey** [comment]
@Vibing 好的，会补充设计思路的。之后也会给出项目开发的脚手架，包括文件结构等。

**Comment by hfuuss** [comment]
mark，期待成品

**Comment by zinkey** [comment]
设计原则：https://bbxjs.github.io/start/principles.html
