### ISSUE TITLE
connect如果连接的是PureComponent，更新state就无法重新渲染了

### ISSUE THREAD

**Issue by deepred5** [bbxjs/bbx#4]
我看`connect.js`源码里，最后
```javascript
return <A {...this.props} />;
```
如果A是PureComponent，state的数据并不是通过props传进去的，所以导致A不再更新渲染了，也就失去了对state的连接

**Comment by zinkey** [comment]
对于 connect 是不能用于 connect pure component 的。connect 是一个简单的的方法，没有 stateToProps。对于这个问题，可采用 https://stackblitz.com/edit/bbx-example-pure 的方式

```jsx
class Pure extends React.PureComponent {
  render() {
    return <div>
      <h1>{countState.state.count}</h1>
      <button onClick={() => countState.add()}>+</button>
      <button onClick={() => countState.minus()}>-</button>
    </div>;
  }
}

const App = connect(countState)(() => <Pure state={countState.state} />);
```

另外，也可采用自定义 connect，stateToProps，之后使用 props，不过不推荐。

**Comment by zinkey** [comment]
另外对于 React.PureComponent 只是比 React.Component 多了对 state 和 props 的 shallowequal。所以可就用 PureComponent，要是有性能要求了，再用 @update 就行了 https://bbxjs.github.io/start/update.html 而不需要用 React.PureComponent。

要是就想用 React.PureComponent，也可将 state 传给 Pure 组件作为 props 使用：

```jsx
class Pure extends React.PureComponent {
  render() {
    return <div>
      <h1>{this.props.count}</h1>
      <button onClick={() => this.props.add()}>+</button>
      <button onClick={() => this.props.minus()}>-</button>
    </div>;
  }
}

@connect(countState)
class App extends React.Component {
  render() {
    return <Pure
       count={countState.state.count}
       add={countState.state.add}
       minus={countState.state.minus}
    />
  }
}
```

bbx 需要判断要是 connect 的组件是 PureComponent 就 throw error。

**Comment by zinkey** [comment]
https://github.com/bbxjs/bbx/pull/14
