### ISSUE TITLE
react初学者对bbx的理解

### ISSUE THREAD

**Issue by edisonchan97** [bbxjs/bbx#9]
我是不是可以这么理解，每一个组件或者模块都有一个bbxState， 然后任一模块或组件都可以通过connect连接到某个组件的bbxState，并更新bbxState 是吗？

**Comment by zinkey** [comment]
当你需要一个组件使用 state，那就可 connect 这个组件。可看看 Ant Design Pro bbx 版本：https://github.com/bbxjs/ant-design-pro

公用的 states 放到最外边，跟路由的 states 放到路由里：
https://github.com/bbxjs/ant-design-pro/tree/bbx/src/states
https://github.com/bbxjs/ant-design-pro/tree/bbx/src/pages/Dashboard/states

之后会在文档说明下 bbx 推荐的开发方式。
